# Generated by Django 5.2.6 on 2025-10-22 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(db_column='user_password', max_length=128)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('release_date', models.CharField(db_column='release_date', max_length=255)),
                ('genre', models.CharField(db_column='genre', max_length=100, null=True)),
                ('studio', models.TextField(db_column='studio')),
                ('score', models.DecimalField(db_column='score', decimal_places=1, max_digits=3)),
                ('cover_image', models.CharField(blank=True, db_column='cover_image', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GamePlots',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('full_plot', models.TextField(db_column='full_plot')),
                ('summary', models.TextField(blank=True, db_column='summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='app.games')),
            ],
            options={
                'db_table': 'GamePlots',
            },
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='question')),
                ('answer', models.TextField(db_column='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_user', to='app.usermodel')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_user_games', to='app.games')),
            ],
            options={
                'db_table': 'ChatBot',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_column='viewed_at')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_games_history', to='app.games')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='app.usermodel')),
            ],
            options={
                'db_table': 'UserHistory',
            },
        ),
    ]
