# Generated by Django 5.2.6 on 2025-09-25 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=100, unique=True)),
                ('email', models.CharField(db_column='email', max_length=255, unique=True)),
                ('user_password', models.CharField(db_column='user_password', max_length=255)),
                ('date_joined', models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('release_year', models.IntegerField(db_column='release_year')),
                ('genre', models.CharField(db_column='genre', max_length=100)),
                ('cover_image', models.ImageField(db_column='cover_image', upload_to='covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GamePlots',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('full_plot', models.TextField(db_column='full_plot')),
                ('summary', models.TextField(db_column='summary')),
                ('source_url', models.CharField(db_column='source_url', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='app.games')),
            ],
            options={
                'db_table': 'gameplots',
            },
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='question')),
                ('answer', models.TextField(db_column='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_user', to='app.customuser')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_user_games', to='app.games')),
            ],
            options={
                'db_table': 'chatbot',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_column='viewed_at')),
                ('game_id', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_games_history', to='app.games')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='app.customuser')),
            ],
            options={
                'db_table': 'userhistory',
            },
        ),
    ]
