# Generated by Django 5.2.6 on 2025-09-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbot',
            table='ChatBot',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='gameplots',
            table='GamePlots',
        ),
        migrations.AlterModelTable(
            name='games',
            table='Games',
        ),
        migrations.AlterModelTable(
            name='userhistory',
            table='UserHistory',
        ),
    ]
