# Generated by Django 5.2.6 on 2025-10-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'managed': False},
        ),
    ]
